(defvar countries-map)
(setf countries-map '
(( "Adelie Land" ("Australian Antarctic Territory"
)) ( "Afghanistan" ("People's Republic of China"
 "Iran"
 "Pakistan"
 "Tajikistan"
 "Turkmenistan"
 "Uzbekistan"
)) ( "Akrotiri and Dhekelia" ("Cyprus" "Northern Cyprus"
)) ( "Albania" ("Greece"
 "Kosovo"
 "Macedonia"
 "Montenegro"
)) ( "Algeria" ("Libya"
 "Mali"
 "Mauritania"
 "Morocco"
 "Niger"
 "Tunisia"
 "Western Sahara"
)) ( "American Samoa" (
)) ( "Amsterdam Island and Ile Saint-Paul" (
)) ( "Andorra" ("France"
 "Spain"
)) ( "Angola" ("Democratic Republic of the Congo"
 "Republic of the Congo"
 "Namibia"
 "Zambia"
)) ( "Anguilla" (
)) ( "Antartica Chilena Province" ("Argentine Antarctica"
 "British Antarctic Territory"
)) ( "Antigua and Barbuda" (
)) ( "Argentine Antarctica" ("Antartica Chilena Province"
  "British Antarctic Territory"
)) ( "Argentina" ("Bolivia"
 "Brazil"
 "Chile"
 "Paraguay"
 "Uruguay"
)) ( "Armenia" ("Azerbaijan"
 "Georgia"
 "Iran"
 "Turkey"
 "Nagorno-Karabakh Republic"
)) ( "Aruba" (
)) ( "Ashmore and Cartier Islands" (
)) ( "Australia" (
)) ( "Australian Antarctic Territory" ("Adelie Land"
 "Queen Maud Land"
 "Ross Dependency"
)) ( "Austria" ("Czech Republic"
 "Germany"
 "Hungary"
 "Italy"
 "Liechtenstein"
 "Slovakia"
 "Slovenia"
 "Switzerland"
)) ( "Azerbaijan" ("Armenia"
 "Georgia"
 "Iran"
 "Russia"
 "Turkey"
 "Nagorno-Karabakh Republic"
)) ( "Azores" (
)) ( "Bahamas" (
)) ( "Bahrain" (
)) ( "Baker Island and Howland Island" (
)) ( "Bangladesh" ("Burma"
 "India"
)) ( "Barbados" (
)) ( "Bassas da India, Europa Island, and Juan de Nova Island" (
)) ( "Belarus" ("Latvia"
 "Lithuania"
 "Poland"
 "Russia"
 "Ukraine"
)) ( "Belgium" ("France"
 "Germany"
 "Luxembourg"
 "Netherlands"
)) ( "Belize" ("Guatemala"
 "Mexico"
)) ( "Benin" ("Burkina Faso"
 "Niger"
 "Nigeria"
 "Togo"
)) ( "Bermuda" (
)) ( "Bhutan" ("People's Republic of China"
 "India"
)) ( "Bolivia" ("Argentina"
 "Brazil"
 "Chile"
 "Paraguay"
 "Peru"
)) ( "Bosnia and Herzegovina" ("Croatia"
 "Montenegro"
 "Serbia"
)) ( "Botswana" ("Namibia"
 "South Africa"
 "Zambia"
 "Zimbabwe"
)) ( "Bouvet Island" (
)) ( "Brazil" ("Argentina"
 "Bolivia"
 "Colombia"
 "French Guiana"
 "Guyana"
 "Paraguay"
 "Peru"
 "Suriname"
 "Uruguay"
 "Venezuela"
)) ( "British Antarctic Territory" ("Antartica Chilena Province"
 "Argentine Antarctica"
 "Queen Maud Land"
)) ( "British Indian Ocean Territory" (
)) ( "British Virgin Islands" (
)) ( "Brunei" ("Malaysia"
)) ( "Bulgaria" ("Greece"
 "Macedonia"
 "Romania"
 "Serbia"
 "Turkey"
)) ( "Burkina Faso" ("Benin"
 "Cote d'Ivoire"
 "Ghana"
 "Mali"
 "Niger"
 "Togo"
)) ( "Burma" ("Bangladesh"
 "People's Republic of China"
 "India"
 "Laos"
 "Thailand"
)) ( "Burundi" ("Democratic Republic of the Congo"
 "Rwanda"
 "Tanzania"
)) ( "Cambodia" ("Laos"
 "Thailand"
 "Vietnam"
)) ( "Cameroon" ("Central African Republic"
 "Chad"
 "Republic of the Congo"
 "Equatorial Guinea"
 "Gabon"
 "Nigeria"
)) ( "Canada" ("United States"
)) ( "Cape Verde" (
)) ( "Cayman Islands" (
)) ( "Central African Republic" ("Cameroon"
 "Chad"
 "Democratic Republic of the Congo"
 "Republic of the Congo"
 "South Sudan"
 "Sudan"
)) ( "Chad" ("Cameroon"
 "Central African Republic"
 "Libya"
 "Niger"
 "Nigeria"
 "Sudan"
)) ( "Chile" ("Argentina"
 "Bolivia"
 "Peru"
)) ( "People's Republic of China" ("Afghanistan"
 "Bhutan"
 "Burma"
 "Hong Kong"
 "India"
 "Kazakhstan"
 "North Korea"
 "Kyrgyzstan"
 "Laos"
 "Macau"
 "Mongolia"
 "Nepal"
 "Pakistan"
 "Russia"
 "Tajikistan"
 "Vietnam"
)) ( "Christmas Island" (
)) ( "Clipperton Island" (
)) ( "Cocos  Islands" (
)) ( "Colombia" ("Brazil"
 "Ecuador"
 "Panama"
 "Peru"
 "Venezuela"
)) ( "Comoros" (
)) ( "Democratic Republic of the Congo" ("Angola"
 "Burundi"
 "Central African Republic"
 "Republic of the Congo"
 "Rwanda"
 "South Sudan"
 "Tanzania"
 "Uganda"
 "Zambia"
)) ( "Republic of the Congo" ("Angola"
 "Cameroon"
 "Central African Republic"
 "Democratic Republic of the Congo"
 "Gabon"
)) ( "Cook Islands" (
)) ( "Costa Rica" ("Nicaragua"
 "Panama"
)) ( "Cote d'Ivoire" ("Burkina Faso"
 "Ghana"
 "Guinea"
 "Liberia"
 "Mali"
)) ( "Croatia" ("Bosnia and Herzegovina"
 "Hungary"
 "Montenegro"
 "Serbia"
 "Slovenia"
)) ( "Crozet Islands" (
)) ( "Cuba" (
)) ( "Curacao" (
)) ( "Cyprus" ("Akrotiri and Dhekelia" "Northern Cyprus"
)) ( "Northern Cyprus" ("Akrotiri and Dhekelia"
 "Cyprus"
)) ( "Czech Republic" ("Austria"
 "Germany"
 "Poland"
 "Slovakia"
)) ( "Denmark" ("Germany"
)) ( "Djibouti" ("Eritrea"
 "Ethiopia"
 "Somalia"
 "Somaliland"
)) ( "Dominica" (
)) ( "Dominican Republic" ("Haiti"
)) ( "East Timor" ("Indonesia"
)) ( "Ecuador" ("Colombia"
 "Peru"
)) ( "Egypt" ("Gaza Strip"
 "Israel"
 "Libya"
 "Sudan"
 "Palestinian territories"
)) ( "El Salvador" ("Guatemala"
 "Honduras"
)) ( "Equatorial Guinea" ("Cameroon"
 "Gabon"
)) ( "Eritrea" ("Djibouti"
 "Ethiopia"
 "Sudan"
)) ( "Estonia" ("Latvia"
 "Russia"
)) ( "Ethiopia" ("Djibouti"
 "Eritrea"
 "Kenya"
 "Somalia"
 "South Sudan"
 "Sudan"
 "Somaliland"
)) ( "Falkland Islands" (
)) ( "Faroe Islands" (
)) ( "Fiji" (
)) ( "Finland" ("Norway"
 "Sweden"
 "Russia"
)) ( "France" ("Andorra"
 "Belgium"
 "Germany"
 "Italy"
 "Luxembourg"
 "Monaco"
 "Spain"
 "Switzerland"
)) ( "French Guiana" ("Brazil"
 "Suriname"
)) ( "French Polynesia" (
)) ( "French Southern and Antarctic Lands" (
)) ( "Gabon" ("Cameroon"
 "Republic of the Congo"
 "Equatorial Guinea"
)) ( "The Gambia" ("Senegal"
)) ( "Gaza Strip" ("Egypt"
 "Israel"
)) ( "Georgia" ("Armenia"
 "Azerbaijan"
 "Russia"
 "Turkey"
)) ( "Germany" ("Austria"
 "Belgium"
 "Czech Republic"
 "Denmark"
 "France"
 "Luxembourg"
 "Netherlands"
 "Poland"
 "Switzerland"
)) ( "Ghana" ("Burkina Faso"
 "Cote d'Ivoire"
 "Togo"
)) ( "Gibraltar" ("Spain"
)) ( "Glorioso Islands" (
)) ( "Greece" ("Albania"
 "Bulgaria"
 "Turkey"
 "Macedonia"
)) ( "Greenland" (
)) ( "Grenada" (
)) ( "French Southern and Antarctic Lands" (
)) ( "Guadeloupe" (
)) ( "Guam" (
)) ( "Guatemala" ("Belize"
 "El Salvador"
 "Honduras"
 "Mexico"
)) ( "Guernsey" (
)) ( "Guinea" ("Cote d'Ivoire"
 "Guinea-Bissau"
 "Liberia"
 "Mali"
 "Senegal"
 "Sierra Leone"
)) ( "Guinea-Bissau" ("Guinea"
 "Senegal"
)) ( "Guyana" ("Brazil"
 "Suriname"
 "Venezuela"
)) ( "Haiti" ("Dominican Republic"
)) ( "Heard Island and McDonald Islands" (
)) ( "Honduras" ("Guatemala"
 "El Salvador"
 "Nicaragua"
)) ( "Hong Kong" ("People's Republic of China"
)) ( "Howland Island and Baker Island" (
)) ( "Hungary" ("Austria"
 "Croatia"
 "Romania"
 "Serbia"
 "Slovakia"
 "Slovenia"
 "Ukraine"
)) ( "Iceland" (
)) ( "Amsterdam Island and Ile Saint-Paul" (
)) ( "India" ("Bangladesh"
 "Bhutan"
 "Burma"
 "People's Republic of China"
 "Nepal"
 "Pakistan"
 "Sri Lanka"
)) ( "Indonesia" ("East Timor"
 "Malaysia"
 "Papua New Guinea"
)) ( "Iran" ("Afghanistan"
 "Armenia"
 "Azerbaijan"
 "Iraq"
 "Pakistan"
 "Turkey"
 "Turkmenistan"
 "Nagorno-Karabakh Republic"
)) ( "Iraq" ("Iran"
 "Jordan"
 "Kuwait"
 "Saudi Arabia"
 "Syria"
 "Turkey"
)) ( "Ireland" ("United Kingdom"
)) ( "Isle of Man" (
)) ( "Israel" ("Egypt"
 "Gaza Strip"
 "Jordan"
 "Lebanon"
 "Syria"
 "West Bank"
 "Palestinian territories"
)) ( "Italy" ("Austria"
 "France"
 "San Marino"
 "Slovenia"
 "Switzerland"
 "Vatican City"
)) ( "Jamaica" (
)) ( "Japan" (
)) ( "Jarvis Island" (
)) ( "Jersey" (
)) ( "Johnston Atoll" (
)) ( "Jordan" ("Iraq"
 "Israel"
 "Saudi Arabia"
 "Syria"
 "West Bank"
 "Palestinian territories"
)) ( "Bassas da India, Europa Island, and Juan de Nova Island" (
)) ( "Kazakhstan" ("People's Republic of China"
 "Kyrgyzstan"
 "Russia"
 "Turkmenistan"
 "Uzbekistan"
)) ( "Kenya" ("Ethiopia"
 "Somalia"
 "South Sudan"
 "Tanzania"
 "Uganda"
)) ( "Kerguelen Islands" (
)) ( "Kingman Reef and Palmyra Atoll" (
)) ( "Kiribati" (
)) ( "North Korea" ("People's Republic of China"
 "South Korea"
 "Russia"
)) ( "South Korea" ("North Korea"
)) ( "Kosovo" ("Albania"
 "Macedonia"
 "Montenegro"
 "Serbia"
)) ( "Kuwait" ("Iraq"
 "Saudi Arabia"
)) ( "Kyrgyzstan" ("People's Republic of China"
 "Kazakhstan"
 "Tajikistan"
 "Uzbekistan"
)) ( "Laos" ("Burma"
 "Cambodia"
 "People's Republic of China"
 "Thailand"
 "Vietnam"
)) ( "Latvia" ("Belarus"
 "Estonia"
 "Lithuania"
 "Russia"
)) ( "Lebanon" ("Israel"
 "Syria"
)) ( "Lesotho" ("South Africa"
)) ( "Liberia" ("Guinea"
 "Cote d'Ivoire"
 "Sierra Leone"
)) ( "Libya" ("Algeria"
 "Chad"
 "Egypt"
 "Niger"
 "Sudan"
 "Tunisia"
)) ( "Liechtenstein" ("Austria"
 "Switzerland"
)) ( "Lithuania" ("Belarus"
 "Latvia"
 "Poland"
 "Russia"
)) ( "Luxembourg" ("Belgium"
 "France"
 "Germany"
)) ( "Macau" ("People's Republic of China"
)) ( "Macedonia" ("Albania"
 "Bulgaria"
 "Greece"
 "Kosovo"
 "Serbia"
)) ( "Macquarie Island" (
)) ( "Madagascar" (
)) ( "Madeira" (
)) ( "Malawi" ("Mozambique"
 "Tanzania"
 "Zambia"
)) ( "Malaysia" ("Brunei"
 "Indonesia"
 "Thailand"
)) ( "Maldives" (
)) ( "Mali" ("Algeria"
 "Burkina Faso"
 "Guinea"
 "Cote d'Ivoire"
 "Mauritania"
 "Niger"
 "Senegal"
)) ( "Malta" (
)) ( "Marshall Islands" (
)) ( "Martinique" (
)) ( "Mauritania" ("Algeria"
 "Mali"
 "Senegal"
 "Western Sahara"
)) ( "Mauritius" (
)) ( "Mayotte" (
)) ( "Mexico" ("Belize"
 "Guatemala"
 "United States"
)) ( "Federated States of Micronesia" (
)) ( "Midway Atoll" (
)) ( "Moldova" ("Romania"
 "Ukraine"
 "Transnistria"
)) ( "Monaco" ("France"
)) ( "Mongolia" ("People's Republic of China"
 "Russia"
)) ( "Montenegro" ("Albania"
 "Bosnia and Herzegovina"
 "Croatia"
 "Kosovo"
 "Serbia"
)) ( "Montserrat" (
)) ( "Morocco" ("Algeria"
 "Western Sahara"
 "Spain"
)) ( "Mozambique" ("Malawi"
 "South Africa"
 "Swaziland"
 "Tanzania"
 "Zambia"
 "Zimbabwe"
)) ( "Nagorno-Karabakh Republic" ("Armenia"
 "Azerbaijan"
 "Iran"
)) ( "Namibia" ("Angola"
 "Botswana"
 "South Africa"
 "Zambia"
)) ( "Nauru" (
)) ( "Navassa Island" (
)) ( "Nepal" ("People's Republic of China"
 "India"
)) ( "Netherlands" ("Belgium"
 "Germany"
)) ( "New Caledonia" (
)) ( "New Zealand" (
)) ( "Nicaragua" ("Costa Rica"
 "Honduras"
)) ( "Niger" ("Algeria"
 "Benin"
 "Burkina Faso"
 "Chad"
 "Libya"
 "Mali"
 "Nigeria"
)) ( "Nigeria" ("Benin"
 "Cameroon"
 "Chad"
 "Niger"
)) ( "Niue" (
)) ( "Norfolk Island" (
)) ( "Northern Mariana Islands" (
)) ( "Norway" ("Finland"
 "Sweden"
 "Russia"
)) ( "Oman" ("Saudi Arabia"
 "United Arab Emirates"
 "Yemen"
)) ( "Pakistan" ("Afghanistan"
 "People's Republic of China"
 "India"
 "Iran"
)) ( "Palau" (
)) ( "Palestinian territories" ("Egypt"
 "Israel"
 "Jordan"
)) ( "Kingman Reef and Palmyra Atoll" (
)) ( "Panama" ("Colombia"
 "Costa Rica"
)) ( "Papua New Guinea" ("Indonesia"
)) ( "Paraguay" ("Argentina"
 "Bolivia"
 "Brazil"
)) ( "Peru" ("Bolivia"
 "Brazil"
 "Chile"
 "Colombia"
 "Ecuador"
)) ( "Peter I Island" (
)) ( "Philippines" (
)) ( "Pitcairn Islands" (
)) ( "Poland" ("Belarus"
 "Czech Republic"
 "Germany"
 "Lithuania"
 "Russia"
 "Slovakia"
 "Ukraine"
)) ( "Portugal" ("Spain"
)) ( "Puerto Rico" (
)) ( "Qatar" ("Saudi Arabia"
 "United Arab Emirates"
)) ( "Queen Maud Land" ("Australian Antarctic Territory"
 "British Antarctic Territory"
)) ( "Reunion" (
)) ( "Romania" ("Bulgaria"
 "Hungary"
 "Moldova"
 "Serbia"
 "Ukraine"
)) ( "Ross Dependency" ("Australian Antarctic Territory"
)) ( "Russia" ("Azerbaijan"
 "Belarus"
 "People's Republic of China"
 "Estonia"
 "Finland"
 "Georgia"
 "Kazakhstan"
 "North Korea"
 "Latvia"
 "Lithuania"
 "Mongolia"
 "Norway"
 "Poland"
 "Ukraine"
)) ( "Rwanda" ("Burundi"
 "Democratic Republic of the Congo"
 "Tanzania"
 "Uganda"
)) ( "Saint Barthelemy" (
)) ( "Saint Helena, Ascension and Tristan da Cunha" (
)) ( "Saint Kitts and Nevis" (
)) ( "Saint Lucia" (
)) ( "Saint Martin" ("Sint Maarten"
)) ( "Saint Pierre and Miquelon" (
)) ( "Saint Vincent and the Grenadines" (
)) ( "Samoa" (
)) ( "San Marino" ("Italy"
)) ( "Sao Tome and Principe" (
)) ( "Saudi Arabia" ("Iraq"
 "Jordan"
 "Kuwait"
 "Oman"
 "Qatar"
 "United Arab Emirates"
 "Yemen"
)) ( "Senegal" ("The Gambia"
 "Guinea"
 "Guinea-Bissau"
 "Mali"
 "Mauritania"
)) ( "Serbia" ("Bosnia and Herzegovina"
 "Bulgaria"
 "Croatia"
 "Hungary"
 "Kosovo"
 "Macedonia"
 "Montenegro"
 "Romania"
)) ( "Seychelles" (
)) ( "Sierra Leone" ("Guinea"
 "Liberia"
)) ( "Singapore" (
)) ( "Sint Maarten" ("Saint Martin"
)) ( "Slovakia" ("Austria"
 "Czech Republic"
 "Hungary"
 "Poland"
 "Ukraine"
)) ( "Slovenia" ("Austria"
 "Croatia"
 "Italy"
 "Hungary"
)) ( "Solomon Islands" (
)) ( "Somalia" ("Djibouti"
 "Ethiopia"
 "Kenya"
 "Somaliland"
)) ( "Somaliland" ("Djibouti"
 "Ethiopia"
 "Somalia"
)) ( "South Africa" ("Botswana"
 "Lesotho"
 "Mozambique"
 "Namibia"
 "Swaziland"
 "Zimbabwe"
)) ( "South Georgia and the South Sandwich Islands" (
)) ( "South Sudan" ("Central African Republic"
 "Democratic Republic of the Congo"
 "Ethiopia"
 "Kenya"
 "Sudan"
 "Uganda"
)) ( "Spain" ("Andorra"
 "France"
 "Gibraltar"
 "Portugal"
 "Morocco"
)) ( "Sri Lanka" ("India"
)) ( "Sudan" ("Central African Republic"
 "Chad"
 "Egypt"
 "Eritrea"
 "Ethiopia"
 "Libya"
 "South Sudan"
)) ( "Suriname" ("Brazil"
 "French Guiana"
 "Guyana"
)) ( "Svalbard" (
)) ( "Swaziland" ("Mozambique"
 "South Africa"
)) ( "Sweden" ("Finland"
 "Norway"
)) ( "Switzerland" ("Austria"
 "France"
 "Italy"
 "Liechtenstein"
 "Germany"
)) ( "Syria" ("Iraq"
 "Israel"
 "Jordan"
 "Lebanon"
 "Turkey"
)) ( "Taiwan" (
)) ( "Tajikistan" ("Afghanistan"
 "People's Republic of China"
 "Kyrgyzstan"
 "Uzbekistan"
)) ( "Tanzania" ("Burundi"
 "Democratic Republic of the Congo"
 "Kenya"
 "Malawi"
 "Mozambique"
 "Rwanda"
 "Uganda"
 "Zambia"
)) ( "Thailand" ("Burma"
 "Cambodia"
 "Laos"
 "Malaysia"
)) ( "Togo" ("Benin"
 "Burkina Faso"
 "Ghana"
)) ( "Tokelau" (
)) ( "Tonga" (
)) ( "Transnistria" ("Moldova"
 "Ukraine"
)) ( "Tromelin Island" (
)) ( "Trinidad and Tobago" (
)) ( "Tunisia" ("Algeria"
 "Libya"
)) ( "Turkey" ("Armenia"
 "Azerbaijan"
 "Bulgaria"
 "Georgia"
 "Greece"
 "Iran"
 "Iraq"
 "Syria"
)) ( "Turkmenistan" ("Afghanistan"
 "Iran"
 "Kazakhstan"
 "Uzbekistan"
)) ( "Turks and Caicos Islands" (
)) ( "Tuvalu" (
)) ( "Uganda" ("Democratic Republic of the Congo"
 "Kenya"
 "Rwanda"
 "South Sudan"
 "Tanzania"
)) ( "Ukraine" ("Belarus"
 "Hungary"
 "Moldova"
 "Poland"
 "Romania"
 "Russia"
 "Slovakia"
 "Transnistria"
)) ( "United Arab Emirates" ("Oman"
 "Qatar"
 "Saudi Arabia"
)) ( "United Kingdom" ("Ireland"
)) ( "United States" ("Canada"
 "Mexico"
)) ( "United States Virgin Islands" (
)) ( "Uruguay" ("Argentina"
 "Brazil"
)) ( "Uzbekistan" ("Afghanistan"
 "Kazakhstan"
 "Kyrgyzstan"
 "Tajikistan"
 "Turkmenistan"
)) ( "Vanuatu" (
)) ( "Vatican City" ("Italy"
)) ( "Venezuela" ("Brazil"
 "Colombia"
 "Guyana"
)) ( "Vietnam" ("Cambodia"
 "People's Republic of China"
 "Laos"
)) ( "Wake Island" (
)) ( "Wallis and Futuna" (
)) ( "West Bank" ("Israel"
 "Jordan"
)) ( "Western Sahara" ("Algeria"
 "Mauritania"
 "Morocco"
)) ( "Yemen" ("Oman"
 "Saudi Arabia"
)) ( "Zambia" ("Angola"
 "Botswana"
 "Democratic Republic of the Congo"
 "Malawi"
 "Mozambique"
 "Namibia"
 "Tanzania"
 "Zimbabwe"
)) ( "Zimbabwe" ("Botswana"
 "Mozambique"
 "South Africa"
 "Zambia"
)))
)
