;;23 states
(defvar *23-states*)
(setf *23-states* '(
                    (JK (PN HP))
                    (PN (JK HP HR RJ))
                    (HP (JK PN HR UP))
                    (HR (PN HP RJ UP))
                    (RJ (PN HR UP GJ MP))
                    (UP (HP HR RJ MP))
                    (GJ (RJ MP MH))
                    (MP (GJ RJ UP OR MH))
                    (MH (GJ MP GA KA))
                    (OR (MP WB))
                    (WB (OR MG AS))
                    (AS (WB MG MZ MR NG AR))
                    (AR (AS NG))
                    (MG (WB AS MZ))
                    (MZ (MG AS MR))
                    (MR (MZ AS NG))
                    (NG (MR AS AR))
                    (GA (MH KA))
                    (KA (GA MH KR TN))
                    (KR (KA TN))
                    (TN (KR KA))
                    (AN ())
                    (LK ())
                   ))


;;15 states
(defvar *15-states*)
(setf *15-states* '(
                    (JK (PN HP))
                    (PN (JK HD HR RJ))
                    (HP (JK PN HR UP))
                    (HR (PN HP RJ UP))
                    (RJ (PN HR UP MP GJ))
                    (UP (RJ HP HR MP))
                    (GJ (RJ MP MH))
                    (MP (GJ RJ UP OR))
                    (MH (GJ MP GA KA))
                    (GA (MH KA))
                    (KA (GA MH KR TN))
                    (KR (KA TN))
                    (TN (KR KA))
                    (OR (MP WB))
                    (WB (OR))
                   ))

;;11 states
(defvar *11-states*)
(setf *11-states* '(
                    (JK (PN HP))
                    (PN (JK HP HR RJ))
                    (HP (JK PN HR UP))
                    (HR (PN HP RJ UP))
                    (RJ (PN HR UP GJ MP))
                    (UP (HP HR RJ MP BH))
                    (GJ (RJ MP MH))
                    (MP (GJ RJ UP BH MH))
                    (BH (MP UP))
                    (MH (GJ MP GA))
                    (GA (MH))
                   ))
